// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for TransferUserAuthenticationFunction
 */
export interface TransferUserAuthenticationFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/funcs/transfer-user-authentication.
 */
export class TransferUserAuthenticationFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: TransferUserAuthenticationFunctionProps) {
    super(scope, id, {
      description: 'src/funcs/transfer-user-authentication.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/funcs/transfer-user-authentication.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}